#! /usr/bin/env python3.8

import argparse

parser = argparse.ArgumentParser(description='Search for words including partial word')
parser.add_argument('filename', help='file name in which search will be performed')
parser.add_argument('expr', help='partial (or complete) string to search')

args = parser.parse_args()
expr = args.expr.lower()

with open(args.filename) as f:
        words = f.readlines()

matches = []

# for word in words:
#     if expr in word.lower():
#         matches.append(word)

#print([word.strip() for word in words if expr in word.lower()])
for word in words:
    if expr in word.lower():
        print(f"expr is {expr} and word is {word}")
