#! /usr/bin/env python3.8

import argparse

parser = argparse.ArgumentParser(description='Search for words including partial word')
parser.add_argument('expr', help='partial (or complete) string to search')

args = parser.parse_args()
expr = args.expr.lower()

with open('/usr/share/dict/words') as f:
        words = f.readlines()

        # matches = []

        # for word in words:
        #     if expr in word.lower():
        #         matches.append(word)

print([word.strip() for word in words if expr in word.lower()])
