#! /usr/bin/env python3.8

import sys

print(f"The script name is : {sys.argv[0]}")
print(f"Printing all the argument supplied to this script : {sys.argv[1:]}")
print(f"The first argument is : {sys.argv[1]}")
