#! /usr/bin/env python3.8

import argparse
import sys

# Build the parser
parser = argparse.ArgumentParser(description='Read a file in reverse order')
parser.add_argument('filename', help='the input file to read')
parser.add_argument('--limit', '-l', type=int, help='the number of lines to read')
parser.add_argument('--version', '-v', action='version', version='%(prog)s 1.0')

# Parse the argument
args = parser.parse_args()
print(args)

# Read the file, reverse the content and print
try:
    f = open(args.filename)
    limit = args.limit

except FileNotFoundError as err:
    print(f"Exception : {err}")
    sys.exit(2)
#except:
#    print(f"testing")
else:
    with f:
        lines = f.readlines()
        print(f"This are the lines : {lines}")
        lines.reverse()
        print(f"Reversed lines: {lines}")

        if args.limit:
            lines = lines[:args.limit]

        for line in lines:
            print(line.strip()[::-1])

finally:
    print("End of script")
